[package]
name = "tokio-linux-aio"
version = "0.1.0"
authors = ["Hans-Martin Will <hwill@acm.org>"]
description = "Tokio bindings for Linux kernel AIO"
repository="https://github.com/hmwill/tokio-linux-aio"
license = "MIT"

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
futures = "0.1"
mio = "0.6.13"
aio-bindings = { path = "aio-bindings" }
libc = "0.2"

[workspace]
